- pkg/volumize/volumize.go
The `output` variable should have been filled in after callback
was finished, but it was shadowed by using type inference to
define a new variable of the same name.
> Fix shadowing of `output` variable in callback

- .goreleaser.yml
- fpm/usr/lib/systemd/system/keights-collector.service
- fpm/usr/lib/systemd/system/keights-collector.timer
- fpm/usr/lib/systemd/system/keights-configure.target
- fpm/usr/lib/systemd/system/keights-share.service
- fpm/usr/lib/systemd/system/keights-templatize-etcd.path
- fpm/usr/lib/systemd/system/keights-templatize-etcd.service
- fpm/usr/lib/systemd/system/keights-templatize-kube-apiserver.path
- fpm/usr/lib/systemd/system/keights-templatize-kube-apiserver.service
- fpm/usr/lib/systemd/system/keights-templatize-kube-controller-manager.path
- fpm/usr/lib/systemd/system/keights-templatize-kube-controller-manager.service
- fpm/usr/lib/systemd/system/keights-templatize-kube-proxy.path
- fpm/usr/lib/systemd/system/keights-templatize-kube-proxy.service
- fpm/usr/lib/systemd/system/keights-templatize-kube-scheduler.path
- fpm/usr/lib/systemd/system/keights-templatize-kube-scheduler.service
- fpm/usr/lib/systemd/system/keights-volumize.service
- fpm/usr/lib/systemd/system/kube-proxy.service
- fpm/usr/lib/systemd/system/kubelet.service
- fpm/usr/lib/tmpfiles.d/keights-collector.conf
- fpm/usr/lib/tmpfiles.d/keights.conf
- fpm/usr/share/keights/etcd.yml.template
- fpm/usr/share/keights/kube-apiserver.yml.template
- fpm/usr/share/keights/kube-controller-manager.yml.template
- fpm/usr/share/keights/kube-proxy.yml.template
- fpm/usr/share/keights/kube-scheduler.yml.template
These are being migrated from the `#cloud-config` of EC2 instance
user data. With these unit files and templates included in the
.deb package, the instance user data can be much smaller and can
include mainly just drop-ins with required `Environment` entries.
> Add additional systemd services and template files

- fpm/usr/lib/systemd/system/keights-share.service
- fpm/usr/lib/systemd/system/keights-templatize-etcd.service
- fpm/usr/lib/systemd/system/keights-templatize-kube-controller-manager.service
- fpm/usr/lib/systemd/system/keights-templatize-kube-proxy.service
- fpm/usr/lib/systemd/system/keights-templatize-kube-scheduler.service
This prevents these services from running
`keights-collector.service` every time they run, since it has
already run and modified the file `/run/keights-collector/asg`,
which causes these services to be activated through their
corresponding systemd path units.
> Remove explicit dependencies on `keights-collector.service`

- fpm/usr/lib/systemd/system/keights-collector.service
Because the environment variables for the keights-collector
service are configured through a launch configuration, putting the
name of the ASG into it creates a circular dependency. The
keights collect subcommand has already been updated to do a lookup
on the autoscaling group to get the name, and it needed to be
removed from the systemd unit.
> Remove `KEIGHTS_ASG_NAME` environment variable from systemd unit

- cmd/volumize.go
- pkg/volumize/volumize.go
Increase wait for EBS volume from 10 minutes to a default of 60,
and add a command line option to change the value.
> Modify wait time for volumes

- ci/assets/v1.11/cluster/requirements.txt
- ci/assets/v1.11/cluster/vars.yml
- ci/pipelines/keights.yml
- ci/tasks/build-cluster.yml
- ci/tasks/run-e2e.yml
- keights/resources/usr/lib/systemd/system/keights-templatize-kubeadm-config.service
- keights/resources/usr/share/keights/kubeadm-config.yaml.template
- stack/ansible/keights-stack/README.md
- stack/ansible/keights-stack/tasks/main.yml
- stack/ansible/keights-system/tasks/main.yml
- stack/cloudformation/common.yml
- stack/cloudformation/master.yml
This includes a change to the `keights-system` Ansible role to
wait for the network, otherwise `sonobuoy`, used for running the
e2e tests, can fail to start properly. And because `sonobuoy`
keeps running on exit, the pod does not restart and recover.
This also changes the default cluster domain from `k8s.local` to
`cluster.local`, as setting to anything other than `cluster.local`
causes DNS e2e tests to fail. This may be overridden with Ansible
and CloudFormation parameters.
> Add e2e tests to Concourse pipeline

- ci/tasks/build-ami.yml
The build-ami Concourse task may be called with a version that
begins with a `v` or not, so this ensures that the version passed
to Packer always starts with `v`.
> Fix version so it always starts with `v` character

- ci/tasks/make-keights.yml
- stack/ansible/keights-stack/README.md
- stack/ansible/keights-stack/tasks/main.yml
- stack/cloudformation/common.yml
- stack/cloudformation/master.yml
For etcd hostnames, it may be desirable to use an existing Route53
zone instead of creating one for each cluster. This adds parameters
for specifying a zone that is unmanaged by this automation.
> Add the ability to override Route53 zone with an unmanaged zone

- pkg/volumize/volumize.go
- stack/cloudformation/master.yml
This improves the volumize command:
The `WaitForVolume()` function adds `status: available` to its
filters when querying AWS. This should make the `AttachVolume`
operation more likely to succeed. Retry is also added around
`AttachVolume` so that it does not abort on the first error.
Length of time to attach and wait for volume is also increased.
The master.yml CloudFormation template has the timeout for
receiving a signal from masters increased to 30 minutes, for cases
where volumize is taking especially long to run.
> Improve resiliency of master initialization

- ci/pipelines/keights.yml
- ci/tasks/verify-release.yml
This is intended to ensure that the release has been tested by the
pipeline. It checks the PR git ref against the tagged git ref,
and fails if they do not match. It also checks the Kubernetes
version against the one most recently tested.
> Add release verification step to Concourse pipeline

- stack/ansible/keights-stack/tasks/main.yml
- stack/ansible/keights-system/README.md
- stack/ansible/keights-system/templates/manifests/calico.yml.j2
- stack/ansible/keights-system/templates/manifests/kube-router.yml.j2
- stack/cloudformation/common.yml
- stack/cloudformation/master.yml
- stack/cloudformation/node.yml
When kube-router handles disabling of source dest check, it can
cause EC2 throttling if the cluster size gets large enough. This
ensures that the attribute is only set once on instance launch,
and disables kube-router from setting the attribute. This also
modifies calico to use `CrossSubnet` mode for IPIP, since the
Lambda can now set the attribute, whereas before it was unset when
using calico.
> Use Lambda to disable source dest check on EC2 instances

- ci/pipelines/keights.yml
The ensure block to upload e2e results to S3 should only run on
the `run-e2e` task, not the whole job.
> Move Concourse pipeline "ensure" block

- stack/ami/debian/build.json
- stack/ami/debian/playbook.yml
Debian stable is now buster, which causes breakage due to iptables
update, see https://github.com/kubernetes/kubernetes/issues/71305.
> Pin Debian release to stretch instead of stable

- stack/ansible/keights-system/README.md
- stack/ansible/keights-system/templates/manifests/calico.yml.j2
This updates cluster-proportional-autoscaler to a newer version to work with
Kubernetes 1.16, and modifies RBAC for 1.16.
> Update calico-typha cluster-proportional-autoscaler

- Makefile
- README.md
- ci/assets/v1.16/cluster/playbook.yml
- stack/ansible/keights-system/README.md
- stack/ansible/keights-system/tasks/main.yml
- stack/ansible/keights-system/templates/manifests/calico.yml.j2
- stack/ansible/keights-system/templates/manifests/kube-router.yml.j2
This adds the ability to configure kube-router or calico to use route reflectors based on node labels.
> Route reflectors

- stack/cloudformation/common.yml
* Masters can communicate with each other only on required ports
* Nodes can communicate with Masters only on required ports
> Tighten security groups

- ci/pipelines/keights.yml
- stack/ami/debian/build.json
- stack/ami/debian/playbook.yml
This replaces the deprecated `jtarchie/pr` with `teliaoss/github-pr-resource`.
> Update Concourse pipeline to use newer GitHub PR resource

- ci/tasks/verify-release.yml
With the newer `teliaoss/github-pr-resource` Concourse resource being used for
GitHub PRs, comparison of git commits works differently. This changes the task
to look in a file written by the resource to get the head commit of the PR.
> Fix pipeline task comparing git commits

- ci/pipelines/keights.yml
- ci/tasks/build-ami.yml
- ci/tasks/build-cluster.yml
- ci/tasks/delete-cluster.yml
- ci/tasks/make-keights.yml
- ci/tasks/run-e2e.yml
- ci/tasks/s3-upload.yml
- ci/tasks/verify-release.yml
To avoid docker hub rate limiting, images will be pulled from
cloudboss.jfrog.io/containers.
> Update CI images to use a registry mirror

- ci/pipelines/keights.yml
This is added so that the whole pipeline doesn't fail if there is an error
when deleting the stack.
> Use `try` on pipeline `ensure` step

- stack/ansible/keights-system/templates/manifests/kube-router.yml.j2
- stack/cloudformation/master-external.yml
- stack/cloudformation/master-stacked.yml
- stack/cloudformation/node.yml
Kube-router needs to communicate with the apiserver on the load balancer when
`replace_kube_proxy: true`. This writes the DNS name of the load balancer to a
file on all instances so it can be mounted as a volume for kube-router. An init
container uses the value from the file to expand a kubeconfig template
placeholder.
This also modifies the kube-router manifest to store the kubeconfig template in a
ConfigMap instead of writing it with a shell heredoc.
> Pass apiserver into instances from CloudFormation

- stack/ami/debian/playbook.yml
This fixes an intermittent crash when starting kube-router. See
https://github.com/cloudnativelabs/kube-router/issues/1155.
> Run iptables in legacy mode

- stack/ansible/keights-system/README.md
- stack/ansible/keights-system/tasks/main.yml
- stack/ansible/keights-system/templates/manifests/aws-ebs-csi-driver.yml.j2
- stack/ansible/keights-system/templates/manifests/cert-manager-crd.yml.j2
- stack/ansible/keights-system/templates/manifests/cert-manager.yml.j2
- stack/ansible/keights-system/templates/manifests/external-snapshotter-crd.yml.j2
- stack/ansible/keights-system/templates/manifests/snapshot-controller.yml.j2
This is to support CSI Migration updates as of Kubernetes 1.23.0.
Changes include:
* aws-ebs-csi-driver deployment
* ebs-csi-node daemonset
* snapshot-controller deployment
* snapshot-validation-webhook deployment
* cert-manager, to generate the keypair for snapshot-validation-webhook
> Add AWS EBS CSI driver
